environment:
  matrix:
    - TOXENV: flakes
    - TOXENV: py26
    - TOXENV: py27
    - TOXENV: py33
    - TOXENV: py34
    - TOXENV: py35
    - TOXENV: py36

matrix:
  fast_finish: true

build: false  # Not a C# project
install: C:\Python36\python -m pip install --pre -U tox
test_script: C:\Python36\scripts\tox
after_test:
  - if exist .coverage.* (C:\Python36\scripts\tox -e coverage) else (echo no .coverage files)
  - if exist coverage.xml (C:\Python36\scripts\tox -e codecov) else (echo no coverage.xml)
