# Ref: https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
blank_issues_enabled: true # default
contact_links:
  - name: ğŸ¤·ğŸ’»ğŸ¤¦ Discussions
    url: https://github.com/tox-dev/tox/discussions
    about: |
      Ask typical Q&A here. Please note that we cannot give support about Python packaging in general, questions about structuring projects and so on.
  - name: ğŸ“ PyPA Code of Conduct
    url: https://www.pypa.io/en/latest/code-of-conduct/
    about: â¤ Be nice to other members of the community. â˜® Behave.
